### ISSUE TITLE
Not Issue but suggestion

### ISSUE THREAD

**Issue by malloryDuke** [Intro-to-SE-Lab-Fall-20/Group-10#10]
I was doing the class diagram for the Controller and it seems that we could just make some attributes global instead of having to pass them through the methods. Idk how you feel about that but just throwing it out

**Comment by NathanCheshire** [comment]
Okay, which attributes do you suggest to make global (public static variables)? The only one I would advise not to would be the password character array.

**Comment by malloryDuke** [comment]
I was thinking mainly email

**Comment by NathanCheshire** [comment]
Sure, would you like me to do that and make sure SS still works? Also I think you have a branch you need to merge sometime before Friday.

**Comment by malloryDuke** [comment]
if you want and i think that is to merge the master into mduke. but i will do that

**Comment by NathanCheshire** [comment]
Email var made static and merged branches so closed issue/suggestion
