### ISSUE TITLE
#FXML Load Exception

### ISSUE THREAD

**Issue by malloryDuke** [Intro-to-SE-Lab-Fall-20/Group-10#5]
Tried to login using straightshot test email. received this exception:
javafx.fxml.LoadException: 
/C:/Users/Owner/OneDrive/Fall2020/introToSE/Group-10/out/production/Group-10/email.fxml

**Comment by NathanCheshire** [comment]
Can you be a big more descriptive. The only thing I can think of is that it's something to do with MS OD or possibly you haven't pulled recently.

**Comment by malloryDuke** [comment]
<img width="960" alt="2020-09-22" src="https://user-images.githubusercontent.com/69919745/93929101-f4505280-fce0-11ea-81f1-41f7ed5cc10b.png">

**Comment by NathanCheshire** [comment]
Can you show your project hierarchy inside of IntelliJ?

**Comment by malloryDuke** [comment]
<img width="214" alt="projectHierarchy" src="https://user-images.githubusercontent.com/69919745/93934013-24e7ba80-fce8-11ea-8854-a5947df718c9.PNG">

**Comment by malloryDuke** [comment]
fixed and added a description to wiki
