### ISSUE TITLE
User Story 5 Issue

### ISSUE THREAD

**Issue by malloryDuke** [Intro-to-SE-Lab-Fall-20/Group-10#7]
The choicebox allows the user to choose between two style files, however the style does not change to the user's choice. Should be resolved by sprint 3.

**Comment by NathanCheshire** [comment]
Just to comment on this, I looked into changing the CSS style within run-time and it seems to be very tricky. I think the best thing we could and should do would be to store what the user most recently chose and then the next time the program is run, use that style.

**Comment by malloryDuke** [comment]
I was thinking we can store the usernames and themes of every valid user in a separate text file and pull from that upon login then change the theme.

**Comment by malloryDuke** [comment]
like the login screen always stays as default but then the other interfaces change to the chosen theme

**Comment by NathanCheshire** [comment]
Yeah that's what I was planning on doing "like the login screen always stays as default but then the other interfaces change to the chosen theme" but do you also want to save a specific email and associated style so that when/if they log back in with that email, that specific theme is used again?
